name: Mobile Compression

on:
  workflow_dispatch:

jobs:
  compress:
    name: Run ASTC Compressor
    runs-on: [self-hosted, linux]

    permissions:
      contents: write

    steps:
      - name: Download Source Code
        uses: actions/checkout@main
        with:
          path: 'repo'

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install ASTC Compressor
        run: haxelib --quiet --always git astc-compressor https://github.com/KarimAkra/astc-compressor develop
        working-directory: repo

      - name: Retrieve Asset Cache
        id: fetch-asset-cache
        uses: actions/cache/restore@main
        with:
          path: repo/astc-textures/**
          key: astc-${{ hashFiles('repo/**.png') }}
          restore-keys: astc-

      - name: Run ASTC Compressor
        run: haxelib run astc-compressor compress-from-json -json ./astc-compression-data.json
        working-directory: repo

      - name: Save Asset Cache
        uses: actions/cache/save@main
        if: steps.fetch-asset-cache.outputs.cache-hit != 'true'
        with:
          path: repo/astc-textures/**
          key: ${{ steps.fetch-asset-cache.outputs.cache-primary-key }}

      - name: Overwrite PNGs with ASTCs
        run: |
          find "astc-textures/" -name "*.astc" -type f | while read -r file; do
            echo "$file"
            normalFileLoc="${file#astc-textures/}"
            normalFilePng="${normalFileLoc%.*}.png"

            if [ -f "$normalFilePng" ]; then
              mv "$file" "$normalFileLoc"
              rm "${normalFilePng}"
            else
              rm "$file"
            fi
          done
        working-directory: repo

      - name: Upload Mobile Artifact
        uses: actions/upload-artifact@main
        with:
          name: mobile
          path: |
            repo/
            !repo/astc-textures/

